### ISSUE TITLE
How to take a screenshot?

### ISSUE THREAD

**Issue by hugows** [raff/godet#10]
Hi,
are there any pointers on  how I would go about taking a screenshot with this or something like this?
I'm not aware if this is something headless chrome can do, or the operating system.
thanks!

**Comment by raff** [comment]
There are a couple of methods (CaptureScreenshot and SaveScreenshot) and an example of the use in the provided example app:
```
	if *screenshot {
		remote.CallbackEvent("DOM.documentUpdated", func(params godet.Params) {
			log.Println("document updated. taking screenshot...")
			remote.SaveScreenshot("screenshot.png", 0644, 0, false)
		})
	}
```
