### ISSUE TITLE
Consider exporting sendRequest while the API is incomplete

### ISSUE THREAD

**Issue by ictran** [raff/godet#13]
Since a lot of APIs are not yet implemented in godet, I think exposing something like the sendRequest method would be useful.

This way, users can use godet to access APIs that are not yet implemented in godet. For example, I needed to capture the screenshot in a specific size, but I had no way to call `Emulation.setVisibleSize` with godet. If we had `SendRequest`, I could simply call it this way:

```go
godet.SendRequest("Emulation.setVisibleSize", godet.Param{})
```

**Comment by raff** [comment]
Ok, let me think about it.
