### ISSUE TITLE
All screenshots blank?

### ISSUE THREAD

**Issue by icco** [raff/godet#14]
So I wrote https://github.com/icco/archive.city/blob/master/main.go, heavily basing it off of your two great examples. All of my screenshots end up blank though. All I want to do is load a web page, take a screenshot of it (eventually I'd love a fullscreen screenshot, but that's for later), and exit.

**Comment by icco** [comment]
Example run:

```
$ go run main.go
2017/05/06 02:08:00 open "/Applications/Google Chrome.app" --args --remote-debugging-port=9222 --disable-extensions --disable-gpu --window-size=1440,900 --headless about:blank
2017/05/06 02:08:00 connect Get http://localhost:9222/json/list: dial tcp [::1]:9222: getsockopt: connection refused
2017/05/06 02:08:00 connected to HeadlessChrome/59.0.3071.36 protocol version 1.2
requestWillBeSent Document https://natwelch.com/ https://natwelch.com/
responseReceived Document https://natwelch.com/
2017/05/06 02:08:00 document updated. taking screenshot...
requestWillBeSent Other https://natwelch.com/ https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css
requestWillBeSent Other https://natwelch.com/ https://natwelch.com/i/dots.png
requestWillBeSent Other https://natwelch.com/ https://natwelch.com/js/jquery.min.js?v=2.2.0
requestWillBeSent Other https://natwelch.com/ https://natwelch.com/js/moment.min.js?v=2.11.1
requestWillBeSent Other https://natwelch.com/ https://natwelch.com/js/nat.js?v=2017-03-03
responseReceived Script https://natwelch.com/js/jquery.min.js?v=2.2.0
responseReceived Image https://natwelch.com/i/dots.png
responseReceived Script https://natwelch.com/js/moment.min.js?v=2.11.1
responseReceived Stylesheet https://unpkg.com/tachyons@4.7.0/css/tachyons.min.css
responseReceived Script https://natwelch.com/js/nat.js?v=2017-03-03
requestWillBeSent Other https://natwelch.com/ https://www.google-analytics.com/analytics.js
requestWillBeSent XHR https://natwelch.com/ https://writing.natwelch.com/posts.json
2017/05/06 02:08:01 document updated. taking screenshot...
responseReceived Script https://www.google-analytics.com/analytics.js
requestWillBeSent Other https://natwelch.com/ https://www.google-analytics.com/r/collect?v=1&_v=j53&a=1223343069&t=pageview&_s=1&dl=https%3A%2F%2Fnatwelch.com%2F&ul=en-us&de=UTF-8&dt=Nat%20Welch%20dot%20com&sd=24-bit&sr=1680x1050&vp=1440x900&je=0&_u=IEAAAEABI~&jid=1337470278&gjid=673415614&cid=1972760275.1494036481&tid=UA-333449-2&_gid=1551872647.1494036481&_r=1&z=282356889
responseReceived Image https://www.google-analytics.com/r/collect?v=1&_v=j53&a=1223343069&t=pageview&_s=1&dl=https%3A%2F%2Fnatwelch.com%2F&ul=en-us&de=UTF-8&dt=Nat%20Welch%20dot%20com&sd=24-bit&sr=1680x1050&vp=1440x900&je=0&_u=IEAAAEABI~&jid=1337470278&gjid=673415614&cid=1972760275.1494036481&tid=UA-333449-2&_gid=1551872647.1494036481&_r=1&z=282356889
responseReceived XHR https://writing.natwelch.com/posts.json
^Csignal: interrupt
```

Example screenshots

[screenshot-20170506020800](https://cloud.githubusercontent.com/assets/20201/25769095/7d864c4c-31df-11e7-86f4-05855079aef8.png)

[screenshot-20170506020801](https://cloud.githubusercontent.com/assets/20201/25769096/7d881c2a-31df-11e7-9f17-5f2ddd614f8e.png)

**Comment by raff** [comment]
Are you using headless_shell or latest Chrome ?

I have noticed (but I should try again) that using "Chrome --headless" on OSX the browser starts minimized and screenshots are empty. If you start the browser without --headless (run godet -?, then copy the URL without --headless) you should see the browser react to your application commands, and in that case taking screenshots will work.

I have to try again, making sure I have the latest headless_shell and Chrome, but I believe this is a problem with headless browser, not with godet.

**Comment by icco** [comment]
I'm using the chrome beta track. It's not starting minimized as far as I
can tell. I'll try on Linux tomorrow and see if I see the same results.

**Comment by raff** [comment]
Ok, I tried again, with results slightly different than yours (I could get screenshot if the browser window is visible, but not if it's hidden) and found out that you need to use "fromSurface=true" in SaveScreenshot to get reliable images (somebody contributed the code, the protocol documentation doesn't say much, and I didn't pay much attention).

Try that and let me now. Also, you may want to download the Canary build, that at least was taking the correct image when the window was open.

And, in case you are interested, I also added SavePDF to save the full page as PDF file.

**Comment by raff** [comment]
https://github.com/raff/godet/commit/05020a8462fecb75087ace6f166cc78f7b6dd2d7

**Comment by icco** [comment]
Using `fromSurface=true` in my code fixed my issue. Thanks @raff !
