### ISSUE TITLE
Reconnecting to a new chrome instance after old one was violently closed

### ISSUE THREAD

**Issue by honzajde** [raff/godet#15]
1. I use godet with a chrome instance
2. I close that instance and open a new one
3. I am trying to connect to a newly opened instance of chrome: 
```go
rem, err := godet.Connect("localhost:9222", false)
// err == nil
```
Then activate tab fails:
```go
err := remote.ActivateTab(tab)
// err = websocket: bad handshake
``` 
Not possible, unless I restart process.

Apart from that (another not resilient usecase):
Closing a tab in chrome and then trying to use it (I keep slice of tabs locally) 
```
2017/05/11 23:24:20 read message: read tcp 127.0.0.1:49192->127.0.0.1:9222: use of closed network connection // after closing it in chrome 
2017/05/11 23:24:21 <nil> // after program call to: err := remote.ActivateTab(tab) log.Println(err)
```
Ok, connection was closed, but hey - no error;)

**Comment by raff** [comment]
I am not sure I understand how to reproduce the problem. Can you share some runnable code ?

Also, did you fetch the latest version of godet ? One of the last changes I made was related to ActivateTab after a disconnession:

https://github.com/raff/godet/commit/16b9d55a86f528f2447e976e4ddd3f1612269646

**Comment by honzajde** [comment]
I have updated my code circa 5 days ago, this change you mention should be in. 
To reproduce:
1. connect with remote 
2. list tabs and keep them in slice
3. close chrome
4. open chrome
5. reconnect with  remote
```go
rem, err := godet.Connect("localhost:9222", false)
// err == nil
```
6. iterate over tabs with `remote.AvtivateTab()` // e.g. you want to load some urls in them; and yes, these tabs don't exist (new instance), should try to list first but b/c of error makes no difference
```go
err := remote.ActivateTab(tab)
// err = websocket: bad handshake
```

**Comment by honzajde** [comment]
btw. I see many times you use `if len(tab.WsURL) == 0` why not just `if tab.WsURL == ""` it's 2017:)

**Comment by raff** [comment]
ActivateTab should now return a proper error (forgot that I also had to check the status on HTTP requests ):

https://github.com/raff/godet/commit/0f3e8fbc05ea200c9ff476c6770561ca2ecae06f

Regarding len(string) == 0, is as good as string == "", independent of the year :)
