### ISSUE TITLE
where is CallbackEvent 

### ISSUE THREAD

**Issue by xfort** [raff/godet#16]
hello.
remote.CallbackEvent(eventname,*);
where is eventname?
What it contains？
Forgive my bad English。
Thanks！

**Comment by raff** [comment]
I don't have constants for the events. You need to look at the devtools protocol.

For example, look at the definition of Network.requestWillBeSent here: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

If you want a package that defines all the events, you can check out https://github.com/knq/chromedp
