### ISSUE TITLE
read message:websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by xfort** [raff/godet#17]
RemoteDebugger.EvaluateWrap(jsString),
if len(jsString)>2000, it do not work

**Comment by raff** [comment]
I can reproduce the problem, with a bigger string. But I think it's a problem with headless chrome.
I'll see if I can report the bug.

**Comment by xfort** [comment]
I use  "github.com/knq/chromedp" to do a test,it can work (send bigger string ).
And, I find you use the same "github.com/gorilla/websocket".
I do not like "chromedp",too cumbersome.
Maybe it is not bug of chrome.
I hope you can understand my bad English。
0.0

**Comment by xfort** [comment]
env :  go_version=1.8.1
           OS=macOSX
           Chromium start cmd=--no-default-browser-check --remote-debugging-port=9222

**Comment by raff** [comment]
You were right. I looked at chromedp and fixed my side. Thanks!

https://github.com/raff/godet/commit/3a46de021a614e5e7d962aa020f9ed981429b25a
