### ISSUE TITLE
Can godet create timeline trace profiles?

### ISSUE THREAD

**Issue by variadico** [raff/godet#22]
I found the `StartProfiler` and `StopProfiler` functions for creating JS profile, but recent versions of Chrome now show this in the Dev Tools.

> The JavaScript CPU profiler will be removed shortly.

I think this happened after version 59. Seems like Google wants people to move to using Timeline profiles, I think. Or maybe some new profile that's a combination of Timeline and CPU profiles.

https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference

Can godet create profiles compatible with the Performance panel?

**Comment by raff** [comment]
Sorry for the long delay. I have added some APIs for the "Profiler" domain:
- StartPreciseCoverage
- StopPreciseCoverage
- GetPreciseCoverage

I didn't exactly understand how to use them exactly, but I tried a couple of things in examples/example.go

Would this work for you ?
