### ISSUE TITLE
Add an ability to disable logging (or provide custom logger)

### ISSUE THREAD

**Issue by iafan** [raff/godet#24]
Currently the code depends on the standard "log" package and there's no way to disable logging (which is quite verbose).

It would be nice if there was an ability to disable logging whatsoever, or expose the `Logger` interface with one `Println` method that external consumer could provide an implementation of (via e.g. `SetLogger(logger Logger)` method). In the second case providing a nil logger could also mute the logging.

**Comment by raff** [comment]
Did you try remote.Connect without the "verbose" flag set ?
https://godoc.org/github.com/raff/godet#Connect

My example sets the verbose flag to show some results. But in a real application you would set it only in debugging mode.

**Comment by iafan** [comment]
I somehow overlooked that. Yes, it solves the original 'disable logging' issue. Still, it would be nice to be able to replace standard logging with something else and remove the hard dependency.

**Comment by raff** [comment]
I am not sure of how I would remove the hard dependency since I would still want to use the standard logging for basic functionalities.

Also, with standard logging you can configure the output and the format. I guess the only thing you wouldn't be able to do would be structured logging (that you could do in only a limited way given that the package controls what it's logging).

**Comment by iafan** [comment]
Well, the standard logging could be done by providing a small wrapper around `log.Println` in the client code. Something like this: https://goplay.space/#ABmEG5hgXj

And instead of passing the boolean verbose flag to the constructor, once could pass the logger instead, which would be self-explanatory:

```go
remote, err := godet.Connect("localhost:9222", &godet.DefaultLogger{})
```

**Comment by iafan** [comment]
Let me know if you'd like me to do a PR for that.
