### ISSUE TITLE
Bogus error messages displayed after Close()

### ISSUE THREAD

**Issue by iafan** [raff/godet#28]
After I call `remote.Close()` (or when activating another tab), the library always spits these two error messages in the log:

```
2018/02/14 21:55:10 read message: read tcp 127.0.0.1:57401->127.0.0.1:32930: use of closed network connection
2018/02/14 21:55:10 permanent network error
```

These errors are harmless (websocket connection is being closed anyway, that's why reading from a websocket fails in the first place), but they are distracting and can't be muted.

I solved this locally by introducing a `isClosing` flag raised in `Close()` function that can be analyzed in the websocket message reading loop, but I'm not sure if this is the best way to handle the error. Will provide a PR soon for the reference.

**Comment by raff** [comment]
Your pull request wasn't solving the problem completely. Check my latest fix.

**Comment by iafan** [comment]
I can confirm the problem is fixed after the update.
