### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by erikdubbelboer** [raff/godet#30]
When using `NewTab()` immediately after calling `Connect()` it is possible the `readMessages()` goroutine started by `Connct()` hasn't started before `NewTab()` changes `remote.ws`. `NewTab()` then also starts a new `readMessages()` goroutine which will try to read on the same `remote.ws` as the old goroutine. `gorilla/websocket` is not thread safe which means this will cause a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x9dad46]

goroutine 277 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0x0, 0x3, 0xc423f99ce8, 0xc423f99ce8, 0x9e4252, 0xc423e7a98c)
        /home/erik/src/github.com/gorilla/websocket/conn.go:931 +0x26
github.com/gorilla/websocket.(*Conn).ReadMessage(0x0, 0x0, 0xc4200ca100, 0xc42001219a, 0xc4200661b8, 0xc4200121c0, 0x3)
        /home/erik/src/github.com/gorilla/websocket/conn.go:1021 +0x2f
github.com/raff/godet.(*RemoteDebugger).readMessages(0xc423e7a960)
        /home/erik/src/github.com/raff/godet/godet.go:426 +0x7c
created by github.com/raff/godet.(*RemoteDebugger).connectWs
        /home/erik/src/github.com/raff/godet/godet.go:308 +0x42f
```

One solution to fix this would be to add the `ws` as an argument to `readMessages()`.

But I was wondering how open you are to changing the API. The current way tabs are implemented is too limited to be useful. Right now to support multiple tabs I'm forced to create multiple `RemoteDebugger` instances and connect them to the different tabs. I would be much nicer if godet supported this in a cleaner way. I propose that most of the methods from `RemoteDebugger` are moved to the `Tab` struct. This combined with each tab getting its own websocket would mean tab support gets a lot better. It would allow multiple tabs to be used independently without having to `ActivateTab()` all the time and without all tabs sharing the same event handlers.

In theory this could also be done in a backwards compatible way if we keep track of the active tab in `RemoteDebugger` and forward all the methods to this active tab. But of course a cleaner solution would be to break backwards compatibility and move all methods to the `Tab` struct.

**Comment by iafan** [comment]
@erikdubbelboer see if https://github.com/raff/godet/issues/27 is similar (though the panic happens on websocket disconnect). I made the [pull request](https://github.com/raff/godet/pull/29) to fix the panic I'm facing by just avoiding sending the messages on a connection that is about to be closed.

Speaking of using multiple tabs, I also found that their usage is pretty limited (and in my case, I also want better security/isolation between running tasks). DevTools protocol has the notion of [Targets and browser contexts](https://chromedevtools.github.io/devtools-protocol/tot/Target) which might help here. But in my project I decided to go further and always use a throw-away docker container to run each command. See it here: https://github.com/iafan/hc

**Comment by erikdubbelboer** [comment]
I'm not using `remote.Close` so this is a different issue, your pull request will not fix this as in my case `remote.isClosing` will stay false.

I need to load as many pages as fast as possible so using throw-away containers is waaay too slow. That's why I'm using multiple tabs for lower memory usage and each tab is fetching different pages at the same time. I don't think Targets and browser contexts have anything to do with this, they seem to be for using safe browsing and being able to load pages into different context where they don't share cookies and local storage.

**Comment by raff** [comment]
I have just added an example of opening multiple tabs in parallel, since it seems to be a hot topic :)
I will check into your panic. Is this on Linux ? (I normally do all my testing on a Mac)

Regarding changing the API to better support of multiple tabs, it's an interesting idea and I have given it a little thought (again, somebody else had a problem with multiple tabs). While it would make the API more clear and easier to use, using multiple RemoteDebuggers is not really that bad and if you look at it, the RemoteDebugger object is pretty much all about managing the connected tab.

Anyway, again, I will give it some more thought. Thanks!

**Comment by raff** [comment]
Can you update and try again ?

**Comment by erikdubbelboer** [comment]
I can tell you that doesn't fix a thing without even trying. Here is the real problem:

I call `Connect()` which calls `connectWs()` which sets `ws` and starts `readMessages()` in a goroutine.
Now before this goroutine has done anything `Connect()` returns and my code calls `NewTab()` which in turn calls `connectWs()` again which starts another `readMessages()` gorountine.
Now at this point both goroutines actually start and both call `socket()` which returns the exact same `ws` (the one that got set with `NewTab()`). Then they both call `ws.ReadMessage()` on the exact same `ws` instance. `gorilla/websocket` is not designed to be thread safe at all so as you can see this makes things panic immediately.

The fix is to not call `socket()` in `readMessages()` but instead get the socket as argument. In this case the first `readMessages()` goroutine would just try to read from the `ws` that was closed when I called `NewTab()`.

**Comment by raff** [comment]
Ok, please try now.

**Comment by erikdubbelboer** [comment]
Yes that fixes it 👍
