### ISSUE TITLE
Can I get a page HTML without have to open a new tab?

### ISSUE THREAD

**Issue by nicolasassi** [raff/godet#31]
Hi! I'm using godet for webscrapping and would like to know if I could leave the chrome instance which godet is beeing used opened and get the HTML from pages there without have to create a new tab and navigate throw that bacause it takes a lot of machine work and as long as I only need the HTML (which a GET method can do alone) it might be possible. Is it?

**Comment by raff** [comment]
I don't think you can. Chrome requires a tab to use the remote debugging APIs.

What you can do is start by creating an empty tab (with URL "about:blank") and then load your pages in it when you need to (via remote.Navigate). No need to stop Chrome or close the tabs.

As an alternative, if you only need the HTML, why do you want use Chrome vs. simple using Go net/http client ?

**Comment by nicolasassi** [comment]
Thanks for answering that fast! 
My problem is that I'm trying to scrape a very trick website (LinkedIn/Sales/) which redirects simples GET requests to blank page even when using cookies in the request. I thought then to use godet or chomedp to open a chrome instance with which I could login in my account and then use the info from that logged page for scrapping. If I open new tabs using godet after the login page it works perfectly, but opening new tabs just for grabbing HTML is a lot of machine work and I have to open a huge amount of tabs. 
Do you have any suggestions for my problem? I'm kind newbie at Golang and programming...

**Comment by raff** [comment]
Again, if manually you are accessing those pages in the same tab, do the same in your automated app. No need to open new tabs, unless the website requires it.

The other thing you can do is what you suggest, use godet to open a page in chrome and login, then get all the info you need (cookies, headers, whatever) and do the remaining requests via net/http client.

**Comment by raff** [comment]
Also, if you are Italian and want to write in Italian, that works too :)

**Comment by nicolasassi** [comment]
I'm actually Brazilian, maybe my English is affected because of my mother language Portuguese haha
Would it be too much to ask you for some help with this thing I suggested (get all the info you need (cookies, headers, whatever))? As I said I'm new at programming and I'm trying to learn by my self so the chrome debugging protocol, http requests and all this stuff still very kind of a pain. I'm not even sure what info would I need for this task. Any help you could give (considering that this package you've done is a lot already) would be great!

**Comment by nicolasassi** [comment]
All I would like to know, if you could help, is how to get those info using godet and after that how to actually make the requests with this. I can't picture how complicated it can became, but if I have at least a kick start about how to do all of that I could keep studying to improve my code and fix possible erros. Thanks again Raff!
