### ISSUE TITLE
Error when connecting to local host

### ISSUE THREAD

**Issue by CDWJ** [raff/godet#40]
I get this when I try to connect to the local host
<code>cannot connect to Chrome instance: Get http://localhost:9222/json/list: dial tcp [::1]:9222: connect: connection refused</code>
What's the reason?

**Comment by erikdubbelboer** [comment]
That would obviously mean that either Chrome isn't running or it isn't listening for connections. How do you start Chrome?

**Comment by CDWJ** [comment]
I just open it by hand.....

**Comment by erikdubbelboer** [comment]
You have to start chrome with `--remote-debugging-port=9222` to enable remote debugging.

**Comment by raff** [comment]
If you want to start Chrome from your Go application, look at the code in cmd/godet/main.go (note that if you already have Chrome running, it will not start a new instance)
