### ISSUE TITLE
how to make chrome load all resources of the page?

### ISSUE THREAD

**Issue by soulbird** [raff/godet#43]
As the title, the chrome can load all resources of the page only then I call "SavePDF" function, otherwise it can't load `jpg` `html`...etc..only `js` `css` can be load. My code like this
```
remote.SetCacheDisabled(false)
remote.NetworkEvents(true)
remote.PageEvents(true)
remote.DOMEvents(true)

_, _ = remote.Navigate("http://zat00.aytest.top")

_ = remote.SavePDF("page.pdf", 0644)
```

However, I don't want to call SavePDF, because I don't want to create a file. So, I want to know which event can make chrome load all resources, and how can I do ?

**Comment by erikdubbelboer** [comment]
`remote.Navigate` will already make Chrome load the page and all the resources.

**Comment by raff** [comment]
Yes (sorry, I started an answer the order day and then got distracted :)

remote.Navigate will load the full page. 

The example shows various things you can do with the library, you don't need to follow it it to the letter.

But if you need to wait for the page to be fully loaded before you proceed you may want to set some event callback (maybe DOM.documentUpdated) and use it to trigger your processing.

**Comment by soulbird** [comment]
I get the resource url by `Network.requestWillBeSent` event, but if I don't call `SavePDF`, I can just get four urls like `js` and `css`.

**Comment by erikdubbelboer** [comment]
Do you register your `Network.requestWillBeSent` callback before or after you call `remote.Navigate`?

**Comment by soulbird** [comment]
yes, this is my code:
`func google() {
	// connect to Chrome instance
	remote, err := godet.Connect("localhost:9222", true)
	if err != nil {
		fmt.Println("cannot connect to Chrome instance:", err)
		return
	}

	remote.CallbackEvent("Network.requestWillBeSent", func(params godet.Params) {
		fmt.Println("requestWillBeSent",
			/*params["type"],
			params["documentURL"],*/
			params["request"].(map[string]interface{})["url"])
	})

	/*remote.CallbackEvent("Network.responseReceived", func(params godet.Params) {
		fmt.Println("responseReceived",
			params["type"],
			params["response"].(map[string]interface{})["url"])
		//params.Map("response"))
	})*/

	remote.SetCacheDisabled(false)
	remote.NetworkEvents(true)
	remote.PageEvents(true)
	remote.DOMEvents(true)

	_, _ = remote.Navigate("http://zat00.aytest.top")


	// or save page as PDF
	//_ = remote.SavePDF("page.pdf", 0644)
}
`

**Comment by erikdubbelboer** [comment]
Everything works fine when I run this. My guess is that you don't realize that `remote.Navigate` returns before everything on the page is loaded. So maybe you program already quits before the page is done. I'm guessing the call to `remote.SavePDF` either waits for things to load before it renders the PDF or it somehow delays just long enough for you to see the resources load. Try replacing `remote.SavePDF` with a `time.Sleep(time.Minute)` and see what happens.

Waiting for all the resources on the page to finish loading is not a simple problem seeing as JavaScript can load new things at any time. People usually work around this issue by either giving the page a fixed amount of time to load or waiting for events like `DOM.documentUpdated` or `Page.loadEventFired`.

**Comment by soulbird** [comment]
Yes, you are right. I use `time.Sleep(time.Minute)`, it works!  But I can't do like this in my online environment.
As you say  `Waiting for all the resources on the page to finish loading is not a simple problem`, I'll continue to study to solve my problem, and if you have a good idea wish you tell me. Think you very  very much!

**Comment by raff** [comment]
@soulbird, did you try running my "godet" command on your site ?

try:

    go run cmd/godet/main.go  -verbose http://zat00.aytest.top

If that seems to correctly terminate after you page has fully loaded, you can try what I am doing there:

    // create channel for wait for completion
    pwait = make(chan bool)
    // set virtual time policy with 5s timeout (5 "virtual seconds" after all network requests have completed"
    remote.SetVirtualTimePolicy(godet.VirtualTimePolicyPauseIfNetworkFetchesPending,
                        int(5*time.Second/time.Millisecond))

     // enable emulation events
     remote.EmulationEvents(true)
     // set callback for "virtual time timeout"
     remote.CallbackEvent("Emulation.virtualTimeBudgetExpired", func(params godet.Params) {
                pwait <- true
     })

     // navigate
     _, _ = remote.Navigate("http://zat00.aytest.top")

     // wait for completion
     <- pwait

**Comment by soulbird** [comment]
@raff No， I just run your example. And I have knew what happened of my code now. I just need wait to the result of the Chrome return. And `Emulation.virtualTimeBudgetExpired` is a good idea to waiting although I still don't know what happened of the Chrome when this  event fired. Thank you!
