### ISSUE TITLE
Have the `Connect` interface receive a map of headers

### ISSUE THREAD

**Issue by ernesto-alvarado** [raff/godet#47]
Add a `headers` parameter to `Connect` so as to allow modifying the headers of the request. This is needed specifically to send a `Host` header to chrome instances so that it doesn't reject requests from clients residing outside of the machine where it is running.
There are places such as https://github.com/raff/godet/blob/master/godet.go#L531 where the headers are hardcoded to nil where the header map could be easily integrated

**Comment by raff** [comment]
Try latest version:

     remote, err := godet.Connect("localhost:9222", false, Host("hostname.com"), Headers(map[string]string{}))

Note that net/http http.Request has a specific Host property (not sure if it also honors the "Host" header) so I have added a specific Host() option (but you can also pass additional header with the Headers() option).
