### ISSUE TITLE
Open multiple profiles on multiple tabs

### ISSUE THREAD

**Issue by baxiry** [raff/godet#50]
Open multiple profiles on multiple tabs? is it possible ? And how? 
thank you so much

**Comment by raff** [comment]
Check the example https://github.com/raff/godet/blob/master/examples/parallel.go

Basically you need to connect to the browser multiple times (and use one separate "remote" connection per tab).

**Comment by baxiry** [comment]
> Check the example https://github.com/raff/godet/blob/master/examples/parallel.go
> 
> Basically you need to connect to the browser multiple times (and use one separate "remote" connection per tab).

thank you so much
