### ISSUE TITLE
Sending selenium commands

### ISSUE THREAD

**Issue by vbisbest** [raff/godet#52]
Is it possible to have gotdet send selenium commands?  For instance if I have these commands, how can I get the chrome browser to execute them using godet?  Thanks!

{
  "id": "858ff576-3ebd-4a31-baee-62fa56598c8e",
  "version": "2.0",
  "name": "JS",
  "url": "http://localhost:3000",
  "tests": [{
    "id": "10039cd8-4364-4e97-aa42-d97f85b3c8b8",
    "name": "JSTest",
    "commands": [{
      "id": "011beeea-932b-4ff3-92f4-86748ec0dff5",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "5354988e-8d7b-4c1f-99fa-2c999b5484b1",
      "comment": "",
      "command": "setWindowSize",
      "target": "1114x790",
      "targets": [],
      "value": ""
    }, {
      "id": "c831ff0b-a38f-495a-b222-4ccbd460195a",
      "comment": "",
      "command": "mouseOver",
      "target": "css=.buttons:nth-child(8)",
      "targets": [
        ["css=.buttons:nth-child(8)", "css:finder"],
        ["xpath=//button[5]", "xpath:position"]
      ],
      "value": ""

**Comment by raff** [comment]
Sorry, I really don't know how Selenium works. I would think Selenium works "the other way around" (i.e. you send a command to Selenium and it get translated into a browser "debug protocol" command).
