### ISSUE TITLE
Control in a separate window

### ISSUE THREAD

**Issue by baxiry** [raff/godet#53]
Firstly, thank you very much for this wonderful library.

There is a Chrome extension that opens in a separate window. How can I access and control this window
This window cannot access its enspect elemnt

The extension is [Line chrome extension](https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc?utm_source=chrome-ntp-icon)

The purpose is to protect the groups you created from intruders.
the Line API does not provide the control feature I need.
The solution is to build a controller through the browser Or anything else.

Thank you so much.

**Comment by raff** [comment]
Did you try listing the tabs ? A separate window should still be a tab that you can control.
