### ISSUE TITLE
remote.FullfillRequest not working

### ISSUE THREAD

**Issue by GuangxinZhang** [raff/godet#54]
i do like this:

		remote.FullfillRequest(params["requestId"].(string),
			200,
			"OK",
			responseHeaders,
			[]byte("============"),
		)

but it not work!

**Comment by raff** [comment]
The reason is that I mispelled "fulfill" (as "fullfill"), and didn't test it properly.
I am going to push a fix, but I would like to also rename godet.FullfillRequest to godet.FulfillRequest.

**Comment by GuangxinZhang** [comment]
> The reason is that I mispelled "fulfill" (as "fullfill"), and didn't test it properly.
> I am going to push a fix, but I would like to also rename godet.FullfillRequest to godet.FulfillRequest.

Oh, thank you very much.
