### ISSUE TITLE
Interface Conversion Error upon calling remote.SetCookie

### ISSUE THREAD

**Issue by Dynosaur** [raff/godet#55]
Hello, I'm very new to Go, so please excuse me if I made a silly mistake.

My machine is on Windows, using Go v1.16.6. Whenever I call remote.SetCookie, such as this:
`remote.SetCookie(godet.Cookie{Name: "Foo", Value: "Bar"})`
I get this error, every time:
```
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
github.com/raff/godet.(*RemoteDebugger).SetCookie(0xc0001921e0, 0x8c9be3, 0x3, 0x8c9bb9, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Jandro/go/pkg/mod/github.com/raff/godet@v0.0.0-20201220021157-de134fa9a46d/godet.go:1055 +0x598
main.main()
        E:/Users/Jandro/Files/Programming/go/godet-set-cookie/src/main.go:9 +0x98
exit status 2
```
Seems like [this line](https://github.com/raff/godet/blob/de134fa9a46df7700dc19cfc533637b6cfae8e0a/godet.go#L1055) is the culprit. As I'm a beginner, I don't really understand the syntax to know what's happening, so I can't make any suggestions.

[Here's an example repo](https://github.com/Dynosaur/godet-set-cookie-example) that recreates the error (For me, at least).

**Comment by raff** [comment]
Sorry, it appears the definition of Network.setCookie changed and it doesn't return the "success" boolean anymore.
I have just made a fix, please update your report and retry.

**Comment by Dynosaur** [comment]
Yup, looks like it's working now! Thanks for the quick update.
