### ISSUE TITLE
how to set "download_restrictions" by godet?

### ISSUE THREAD

**Issue by terry2010** [raff/godet#58]
I want to block all downloads , but can not find a way to set it. 

selenium could set  download_restrictions :3  to settle this  .

Remote.SetDownloadBehavior(godet.DenyDownload,"/A:")
Tab, err = Remote.NewTab("https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BF49017DD-2E64-6292-C8FB-E1121560FAAA%7D%26lang%3Dzh-CN%26browser%3D3%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26brand%3DYTUH%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe")

not work 

there must a way by godet ,  how to set it , thank you

**Comment by raff** [comment]
This seems to work for me:

`        remote.SetDownloadBehavior(godet.DenyDownload, "")

        // try download
        remote.Navigate("https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BF49017DD-2E64-6292-C8FB-E1121560FAAA%7D%26lang%3Dzh-CN%26browser%3D3%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26brand%3DYTUH%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe")
`
If I comment out the call to SetDownloadBehaviour the file gets downloaded.
