### ISSUE TITLE
Same goal

### ISSUE THREAD

**Issue by neelance** [raff/godet#6]
Hi @raff, I just wanted to make you aware of my cdp-go project which has the same goal as yours: https://godoc.org/github.com/neelance/cdp-go

Key differences are that I leverage the `net/rpc` package to do some heavy lifting for the RPC and that I automatically generate the API from the `browser_protocol.json` found in the Chromium source code. The project is WIP, but I wanted to tell you about it so it maybe saves you some time.

**Comment by raff** [comment]
Thanks! I will keep an eye on this.
