### ISSUE TITLE
Extend EvaluateError

### ISSUE THREAD

**Issue by ghost** [raff/godet#9]
It would be nice when EvaluateError would return the description, lineNumber and columnNumber when the error is of type "SyntaxError".

**Comment by raff** [comment]
I see evaluate can also return an optional "exceptionDetails" object. I'll try to add a test case and see how I can extend the evaluate method or EvaluateError.

**Comment by raff** [comment]
See https://github.com/raff/godet/commit/93514ab7082849a156ed8e99f1be9c822a2173dc
